# Generated by Django 6.1.1 on 2026-09-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='The most recently created active footer is the one rendered.'),
        ),
    ]
