# Generated by Django 6.1.1 on 2026-09-21 16:06

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0098_apitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('og_title', models.CharField(blank=True, help_text="Defaults to the page's SEO title, then the page title.", max_length=95, verbose_name='Social share title')),
                ('og_description', models.TextField(blank=True, help_text='Defaults to the meta description.', max_length=200, verbose_name='Social share description')),
                ('no_index', models.BooleanField(default=False, help_text='Adds a noindex tag. Use for thank-you or landing pages.', verbose_name='Hide from search engines')),
                ('hero_eyebrow', models.CharField(blank=True, help_text='Small line above the headline.', max_length=60)),
                ('hero_heading', models.CharField(blank=True, help_text='The main headline. Defaults to the page title if blank.', max_length=120)),
                ('hero_subheading', models.TextField(blank=True, max_length=300)),
                ('hero_buttons', wagtail.fields.StreamField([('button', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the linked page's title.", 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used only when no page is chosen.', 'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')]}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1), ('external_url', 2), ('style', 3)]], {})}, help_text='Up to two buttons in the hero.')),
                ('body', wagtail.fields.StreamField([('hero', 11), ('rich_text', 12), ('image', 17), ('feature_grid', 25), ('call_to_action', 28), ('testimonial', 30), ('stats', 34), ('faq', 39)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small text above the heading.', 'max_length': 60, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 120}), 2: ('wagtail.blocks.TextBlock', (), {'max_length': 300, 'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('center', 'Centre')]}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the linked page's title.", 'max_length': 80, 'required': False}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site.', 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used only when no page is chosen.', 'label': 'External URL', 'required': False}), 8: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')]}), 9: ('wagtail.blocks.StructBlock', [[('text', 5), ('page', 6), ('external_url', 7), ('style', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'max_num': 2, 'required': False}), 11: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('subheading', 2), ('background_image', 3), ('alignment', 4), ('buttons', 10)]], {}), 12: ('apps.core.blocks.RichTextBlock', (), {}), 13: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 14: ('wagtail.blocks.CharBlock', (), {'max_length': 250, 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'max_length': 120, 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('standard', 'Standard'), ('wide', 'Wide'), ('full', 'Full bleed')]}), 17: ('wagtail.blocks.StructBlock', [[('image', 13), ('caption', 14), ('attribution', 15), ('width', 16)]], {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', 'Two'), ('3', 'Three'), ('4', 'Four')]}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('bolt', 'Bolt'), ('shield', 'Shield'), ('chart', 'Chart'), ('gear', 'Gear'), ('globe', 'Globe'), ('users', 'Users'), ('sparkle', 'Sparkle'), ('check', 'Check')], 'help_text': 'Chosen from a fixed icon set so cards stay consistent.'}), 20: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 21: ('wagtail.blocks.TextBlock', (), {'max_length': 300}), 22: ('wagtail.blocks.StructBlock', [[('text', 5), ('page', 6), ('external_url', 7)]], {'required': False}), 23: ('wagtail.blocks.StructBlock', [[('icon', 19), ('title', 20), ('text', 21), ('link', 22)]], {}), 24: ('wagtail.blocks.ListBlock', (23,), {'min_num': 1}), 25: ('wagtail.blocks.StructBlock', [[('heading', 15), ('intro', 2), ('columns', 18), ('cards', 24)]], {}), 26: ('wagtail.blocks.ListBlock', (9,), {'max_num': 2, 'min_num': 1}), 27: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('accent', 'Accent background'), ('muted', 'Muted background')]}), 28: ('wagtail.blocks.StructBlock', [[('heading', 1), ('text', 2), ('buttons', 26), ('style', 27)]], {}), 29: ('wagtail.blocks.TextBlock', (), {'max_length': 500}), 30: ('wagtail.blocks.StructBlock', [[('quote', 29), ('author_name', 20), ('author_role', 15), ('author_image', 3), ('company_logo', 3)]], {}), 31: ('wagtail.blocks.CharBlock', (), {'help_text': 'For example: 98%, 1.2M, 24/7', 'max_length': 20}), 32: ('wagtail.blocks.StructBlock', [[('value', 31), ('label', 20)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {'max_num': 4, 'min_num': 1}), 34: ('wagtail.blocks.StructBlock', [[('heading', 15), ('stats', 33)]], {}), 35: ('wagtail.blocks.CharBlock', (), {'max_length': 200}), 36: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 37: ('wagtail.blocks.StructBlock', [[('question', 35), ('answer', 36)]], {}), 38: ('wagtail.blocks.ListBlock', (37,), {'min_num': 1}), 39: ('wagtail.blocks.StructBlock', [[('heading', 15), ('items', 38)]], {})}, help_text='Build the page from the available sections.')),
                ('cta_heading', models.CharField(blank=True, max_length=120)),
                ('cta_text', models.TextField(blank=True, max_length=300)),
                ('cta_buttons', wagtail.fields.StreamField([('button', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use the linked page's title.", 'max_length': 80, 'required': False}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Link to a page on this site.', 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Used only when no page is chosen.', 'label': 'External URL', 'required': False}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary'), ('ghost', 'Ghost')]}), 4: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1), ('external_url', 2), ('style', 3)]], {})})),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage')),
                ('og_image', models.ForeignKey(blank=True, help_text='Shown when this page is shared on social media. 1200x630 works best.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.customimage', verbose_name='Social share image')),
            ],
            options={
                'verbose_name': 'Home page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
